### ISSUE TITLE
[Bug] BoomBot can be used to mention @everyone by users without permission to mention @everyone

### ISSUE THREAD

**Issue by TangentFoxy** [Lomeli12/BoomBot#2]
![screenshot from 2016-09-10 13 23 18](https://cloud.githubusercontent.com/assets/15093567/18413346/d189f0aa-7759-11e6-9d13-7c27fc6c6025.png)

**Comment by TangentFoxy** [comment]
This would also apply to @here

**Comment by Lomeli12** [comment]
I'll fix this in v3.x.x
